# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8591e3c5137684a7173846b5969b207a2f590303e82be1fb60aaff04ee7c196535a0b5762756feaa66c368ad7127c2fbf22f23169795d3d83fb9489eed34aeab

test:
  secret_key_base: b78a494cfce62aeba4e6fe0415bb6e80b4a4b2989346242bcb661c0cc2c55c6c96c92c2b4ae141a54fcf455aaa45db5477d2dba7deda67ca9618a4c04feb899e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
